#include "Events.h"

wxDEFINE_EVENT(wxEVT_SERIAL_UPDATE, wxThreadEvent);
wxDEFINE_EVENT(wxEVT_HANDSHAKE, wxThreadEvent);
wxDEFINE_EVENT(wxEVT_PROJECT_NEW, wxCommandEvent);
wxDEFINE_EVENT(wxEVT_START_STOP_TOGGLE, wxCommandEvent);
//wxDEFINE_EVENT(wxEVT_STOP_EXPERIMENT, wxCommandEvent);
wxDEFINE_EVENT(wxEVT_COLLECT_UPDATED, wxCommandEvent);
//wxDEFINE_EVENT(wxEVT_GRAPH_DATA, wxCommandEvent);
wxDEFINE_EVENT(wxEVT_GRAPH_SENSOR, wxCommandEvent);
wxDEFINE_EVENT(wxEVT_COLLECT_NOW_POINT, wxCommandEvent);
wxDEFINE_EVENT(wxEVT_THEME_TOGGLE, wxCommandEvent);
