var annotated_dup =
[
    [ "AddSensorDialog", "classAddSensorDialog.html", null ],
    [ "App", "classApp.html", "classApp" ],
    [ "CalibrateSensorDialog", "classCalibrateSensorDialog.html", null ],
    [ "CalibrationPoint", "structCalibrationPoint.html", null ],
    [ "CalibrationTableDialog", "classCalibrationTableDialog.html", null ],
    [ "Calibrator", "classCalibrator.html", null ],
    [ "DataCollector", "classDataCollector.html", null ],
    [ "DataSession", "classDataSession.html", null ],
    [ "DataTableWindow", "classDataTableWindow.html", null ],
    [ "GraphWindow", "classGraphWindow.html", "classGraphWindow" ],
    [ "HandshakeDialog", "classHandshakeDialog.html", null ],
    [ "Interpolator", "classInterpolator.html", null ],
    [ "LiveDataWindow", "classLiveDataWindow.html", null ],
    [ "MainFrame", "classMainFrame.html", null ],
    [ "MappedReader", "classMappedReader.html", null ],
    [ "ProjectConfigDialog", "classProjectConfigDialog.html", null ],
    [ "ProjectPanel", "classProjectPanel.html", "classProjectPanel" ],
    [ "RawReader", "classRawReader.html", null ],
    [ "ReadingPacket", "structReadingPacket.html", null ],
    [ "ReadingStrategy", "classReadingStrategy.html", null ],
    [ "Run", "classRun.html", null ],
    [ "Sensor", "classSensor.html", null ],
    [ "SensorConfigDialog", "classSensorConfigDialog.html", null ],
    [ "SensorDatabase", "classSensorDatabase.html", null ],
    [ "SensorManager", "classSensorManager.html", null ],
    [ "SensorSelectionDialog", "classSensorSelectionDialog.html", null ],
    [ "SerialComm", "classSerialComm.html", "classSerialComm" ],
    [ "SessionController", "classSessionController.html", "classSessionController" ],
    [ "Sidebar", "classSidebar.html", null ],
    [ "Toolbar", "classToolbar.html", null ],
    [ "VoltageReader", "classVoltageReader.html", null ]
];